#Database Configuration
spring:
  #Se proporciona para la BD 
  datasource:
             url: jdbc:mysql://localhost:3306/recursos_humanos?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
             username: root
             password: admin
             driver-class-name: com.mysql.cj.jdbc.Driver
 