#Se pueden poner comentarios. 
spring:
  cache:
    redis:
      use-key-prefix: true
  jmx:
   enabled: true
   unique-names: false
server:
  jetty:
    acceptors: -1
    accesslog:
      append: false
      date-format: dd/MMM/yyyy:HH:mm:ss